loban_loft/api/urls.py
from django.urls import path, include
from rest_framework.routers import SimpleRouter
from .views import CategoryModelViewSet

router = SimpleRouter()
router.register('category', CategoryModelViewSet)

urlpatterns = [
    path('v1/', include(router.urls))
]

loban_loft/loban_loft/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('api/', include('api.urls')),
    path('', include('shop.urls'))

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'shop.views.page_not_found'

loban_loft/shop/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import *

urlpatterns = [

    path('', ProductListView.as_view(), name='shop_product_list'),
    path('category/', FilterCategoryView.as_view(), name='category'),
    path('contact/', ApplicationListView.as_view(), name='contact'),
    path('register/', RegisterView.as_view(), name='signup'),
    path('login/', SignInView.as_view(), name='signin'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('cart/', CartListView.as_view(), name='shop_cart'),
    path('search/', Search.as_view(), name='search'),
    path('about/', AboutListView.as_view(), name='about'),

    path('<slug:slug>/', ProductDetailView.as_view(), name='shop_product_detail'),
    path('review/<int:pk>/', AddReview.as_view(), name='add_review'),
    # path('user_profile/<int:pk>/', ShowProfilePageView.as_view(), name='user_profile'),

]

loban_loft/shop/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(
        max_length=32,
        verbose_name='название',
        unique=True,
        null=False,
        blank=False
    )

    # slug = models.SlugField(verbose_name='Транслит', null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'category'
        ordering = ['name']
        verbose_name = 'категория товара'
        verbose_name_plural = 'категориии товаров'

    # def __unicode__(self):
    #     return self.name


class Product(models.Model):
    title = models.CharField(
        max_length=32,
        verbose_name='название товара',
        null=False,
        blank=False
    )
    description = models.TextField(
        verbose_name='описание товара',
        max_length=4096,
        null=True,
        blank=True
    )
    descr = models.TextField(
        verbose_name='информация о товаре',
        max_length=4096,
        null=True,
        blank=True,
    )

    slug = models.SlugField(
        verbose_name='URL',
        unique=True,
        null=False,
        blank=False
    )
    category = models.ForeignKey(
        'Category',
        on_delete=models.PROTECT,
        verbose_name='категория'
    )
    image = models.ImageField(
        verbose_name='картинка',
        upload_to='product/',
        null=True,
        blank=True
    )

    price = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        verbose_name='цена',
        null=True,
        blank=True
    )
    is_published = models.BooleanField(
        default=False,
        verbose_name='публикация'
    )


    def get_absolute_url(self):
        return reverse('shop_product_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'


class About(models.Model):
    title = models.CharField(
        max_length=32,
        verbose_name='заглавная стока',
        null=False,
        blank=False
    )
    description = models.TextField(
        verbose_name='вспомогательный текст',
        max_length=4096,
        null=True,
        blank=True
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'о нас'
        verbose_name_plural = 'о нас'


class Application(models.Model):
    name = models.CharField('имя', max_length=32)
    number = models.CharField('номер телефона', max_length=17)
    message = models.CharField('Сообщение', max_length=5000)
    slug = models.SlugField(verbose_name='URL', unique=True, null=False, blank=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'заявка'
        verbose_name_plural = 'заявки'


class ProductImage(models.Model):
    title = models.CharField('Заголовок', max_length=100, null=False, blank=False)
    images = models.ImageField('Изображение', upload_to='products_image/')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'фото к товару'
        verbose_name_plural = 'фото к товару'


class Reviews(models.Model):
    # email = models.EmailField()
    name = models.CharField('Имя', max_length=100)
    text = models.TextField('сообщение', max_length=5000)
    parents = models.ForeignKey(
        'self', verbose_name='Родитель', on_delete=models.SET_NULL, blank=True, null=True
    )
    product = models.ForeignKey(Product, verbose_name='продукт', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} - {self.product}'

    class Meta:
        verbose_name = 'отзыв'
        verbose_name_plural = 'отзывы'


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    is_paid = models.BooleanField(default=False)


    def __str__(self):
        return f'Order{self.pk}'

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING)

    def __str__(self):
        return f'OrderItem{self.order} Product {self.product}'


class Profile(models.Model):
    user=models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    bio=models.TextField(null=True, blank=True)


    def __str__(self):
        return str(self.user)

loban_loft/shop/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django.forms import ModelForm, TextInput, Textarea

from django.utils.translation import gettext as _
from .models import Reviews, Application


class UserRegisterForm(UserCreationForm):
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                'name': 'password1',
                'placeholder': 'Enter Password'
            }
        ),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                'name': 'password1',
                'placeholder': 'Re-Enter Password'
            }
        ),
        strip=False,
        help_text=_("Enter the same password as before, for verification.")
    )
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'name': 'password1',
                'placeholder': 'Enter Username'
            }
        )
    )
    # email = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             'name': 'email',
    #             'placeholder': 'Enter Email'
    #         }
    #     )
    # )


class LoginForm(AuthenticationForm):
    username = UsernameField(
        widget=forms.TextInput(
            attrs={
                'autofocus': True,
                'name': 'password1',
                'placeholder': 'Enter Login'
            }
        )
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                'name': 'password1',
                'placeholder': 'Enter Password'
            }
        ),
    )


class ReviewForm(ModelForm):
    class Meta:
        model = Reviews
        fields = ('name', 'text')


class ApplicationModelForm(ModelForm):
    class Meta:
        model = Application
        fields = ('name', 'number', 'message', 'slug')
        widgets = {
            'name': TextInput(
                attrs={'class': 'form-control', 'id': 'Name', 'placeholder': 'Введите имя'}
            ),
            'number': TextInput(
                attrs={'class': 'form-control', 'id': 'Number', 'placeholder': 'Введите номер'}
            ),
            'message': Textarea(
                attrs={'class': 'form-control', 'id': 'Message', 'placeholder': 'Введите сообщение'}
            ),
            'slug': TextInput(
                attrs={'reqired': False, 'hedden': 'True', 'id': 'slug', 'value': ' '}
            )
        }

loban_loft/shop/views.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.base import View
from django.views.generic import ListView, DetailView, CreateView
from slugify import slugify

from .forms import UserRegisterForm, LoginForm, ReviewForm, ApplicationModelForm
from .models import Product, Category, Order, OrderItem, About, Application, Profile


class SortList:

    def get_sorts(self):
        return Category.objects.all()


class ProductListView(SortList, ListView):
    template_name = 'shop/men.html'
    model = Product
    paginate_by = 2

    def get_queryset(self):
        return Product.objects.filter(is_published=True)


class ProductDetailView(SortList, DetailView):
    template_name = 'shop/single.html'
    model = Product


class FilterCategoryView(SortList, ListView):
    template_name = 'shop/men.html'

    def get_queryset(self):
        queryset = Product.objects.filter(category__in=self.request.GET.getlist("category"))
        return queryset


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    fields = ['profile_pic', 'bio']
    template_name = 'shop/register.html'
    success_url = reverse_lazy('signin')


class SignInView(LoginView):
    form_class = LoginForm
    template_name = 'shop/login.html'


class CartListView(LoginRequiredMixin, ListView):
    model = OrderItem
    template_name = 'shop/checkout.html'
    context_object_name = 'order_item_list'
    login_url = '/login/'

    def get_queryset(self):
        return self.model.objects.filter(Q(order__is_paid=False) & Q(order__user=self.request.user))

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CartListView, self).get_context_data()
        context['total_amount'] = 0
        context['cart_amount'] = len(context[self.context_object_name])
        for product in context[self.context_object_name]:
            context['total_amount'] += product.product.price
        return context


def page_not_found(request, exception):
    print(exception)
    return HttpResponse('<b>404 PAGE NOT FOUND</b>')


class AddReview(View):

    def post(self, request, pk):
        form = ReviewForm(request.POST)
        product = Product.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            form.product = product
            form.save()
        return redirect(product.get_absolute_url())


class Search(ListView):
    paginate_by = 3
    template_name = 'shop/men.html'

    def get_queryset(self):
        return Product.objects.filter(title__icontains=self.request.GET.get('q'))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['q'] = self.request.GET.get('q')
        return context


# class ShowProfilePageView(DetailView):
#     model = User
#     template_name = 'shop/user_profile.html'
#
#     def get_context_data(self, *args, **kwargs):
#         users = Profile.objects.all()
#         context = super(ShowProfilePageView, self).get_context_data(*args, **kwargs)
#         page_user = get_object_or_404(Profile, id=self.kwargs['pk'])
#         context['page_user'] = page_user
#         return context


class AboutListView(ListView):
    template_name = 'shop/about.html'
    model = About


class ApplicationListView(ListView):
    template_name = 'shop/contact.html'
    model = Application
    http_method_names = ('get', 'post')
    context_object_name = 'application_list'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ApplicationListView, self).get_context_data()
        context['application_form'] = ApplicationModelForm
        return context

    def post(self, request: HttpRequest):
        data = request.POST.dict()
        data.update(slug=slugify(request.POST.get('number')))
        form = ApplicationModelForm(data)
        if form.is_valid():
            form.save()
        return self.get(request=request)


# class CreateProfilePageView(CreateView):
#     model = Profile
#
#     template_name = 'shop/create_profile.html'
#     fields = ['profile_pic', 'bio']
#
#     def form_valid(self, form):
#         form.instance.user = self.request.user
#         return super().form_valid(form)
#
#     success_url = reverse_lazy('logout')

loban_loft/shop/templates/shop/about.html
{% extends "shop/base.html" %}

{% block title %}
GANGA_GANGA | О нас
{% endblock %}

{% block content %}
{% include "shop/components/header.html" %}

{% for about in about_list %}
<div class="single_top">
	 <div class="container"> 
	  <div class="box_4">
	  	<div class="col-md-10 about_left">
	  		<h1>{{ about.title}} </h1>
	        <img src="images/banner.jpg" class="img-responsive" alt=""/>
		    <p>{{ about.description }}</p>
{% endfor %}
<!--	       <div class="faqs">-->
<!--				       <h2>Why Choose Us</h2>-->
<!--				       <div class="questions">-->
<!--							<h3>1.What is Lorem Ipsum?</h3>-->
<!--	        				<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>-->
<!--	        		   </div>-->
<!--			        		   <div class="questions">-->
<!--									<h3>2.What is Lorem Ipsum dummy text ever since the 1500s?</h3>-->
<!--			        				<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>-->
			        			</div>
				   </div>
	</div>
	</div>


{% include "shop/components/footer.html" %}
{% endblock %}

loban_loft/shop/templates/shop/base.html
{% load static %}

<!DOCTYPE HTML>
<html>

<head>
<title>{% block title %}{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Buy_shop Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href="{% static 'css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<!-- Custom Theme files -->
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' />
<script src="{% static 'js/simpleCart.min.js' %}"> </script>
<!-- Custom Theme files -->
<!--webfont-->
<link href='http://fonts.googleapis.com/css?family=Lato:100,200,300,400,500,600,700,800,900' rel='stylesheet' type='text/css'>
<script type="text/javascript" src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
<!-- start menu -->
<link href="{% static 'css/megamenu.css' %}" rel="stylesheet" type="text/css" media="all" />
<script type="text/javascript" src="{% static 'js/megamenu.js' %}"></script>
<script>$(document).ready(function(){$(".megamenu").megamenu();});</script>
</head>
<body>
{% block content %}
{% endblock %}


</body>
</html>

loban_loft/shop/templates/shop/checkout.html
{% extends "shop/base.html" %}
{% block title %}
CART
{% endblock %}


{% block content %}
{% include "shop/components/header.html" %}

<div class="container">
	<div class="check">	 

			{% for order_item in order_item_list %}
			{% include "shop/components/cart.html" %}
			{% endfor %}
	</div>
		 <div class="col-md-3 cart-total">
			 <a class="continue" href="#">Continue to basket</a>
			 <div class="price-details">
				 <h3>Price Details</h3>
				 <span>Total</span>
				 <span class="total1">{{ total_amount }}</span>
				 <span>Discount</span>
				 <span class="total1">{{ cart_amount }}</span>
				 <div class="clearfix"></div>				 
			 </div>	
			 <ul class="total_price">
			   <li class="last_price"> <h4>TOTAL</h4></li>	
			   <li class="last_price"><span>{{ total_amount }}</span></li>
			   <div class="clearfix"> </div>
			 </ul>
			
			 
			 <div class="clearfix"></div>
			 <a class="order" href="#">Place Order</a>
			 <div class="total-item">
				 <h3>OPTIONS</h3>
				 <h4>COUPONS</h4>
				 <a class="cpns" href="#">Apply Coupons</a>
				 <p><a href="{% url 'signin' %}">Log In</a> to use accounts - linked coupons</p>
			 </div>

		</div>
</div>
{% include "shop/components/footer.html" %}
{% endblock %}

loban_loft/shop/templates/shop/contact.html
{% extends "shop/base.html" %}

{% block title %}
GANGA_GANGA | Каталог
{% endblock %}

{% block content %}

{% include "shop/components/header.html" %}

<div class="single_top">
	 <div class="container"> 
	  <div class="map">
	     <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d3150859.767904157!2d-96.62081048651531!3d39.536794757966845!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sin!4v1408111832978"> </iframe>
	   </div>
	   <div class="col-md-9 contact_left">
		 	  <h1>Get in Touch</h1>
	  			  <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever </p>
	  			 <form method="post">
					 {% csrf_token%}

					<div class="column_2">

						{{ application_form.name }}

						{{ application_form.number }}
					</div>
					<div class="column_3">

						{{ application_form.message }}
	                </div>
	                <div class="form-submit1">
			          <input type="submit" value="Send Message">

					</div>
					<div class="clearfix"> </div>
				  </form>
		 </div>
		 <div class="col-md-3 contact_right">
		 	<h2>Information</h2>
		 	<address class="address">
              <p>9870 St Vincent Place, <br>Glasgow, DC 45 Fr 45.</p>
              <dl>
                 <dt></dt>
                 <dd>Freephone:<span> +1 800 254 2478</span></dd>
                 <dd>Telephone:<span> +1 800 547 5478</span></dd>
                 <dd>FAX: <span>+1 800 658 5784</span></dd>
                 <dd>E-mail:&nbsp; <a href="mailto@example.com">info(at)lashoop.com</a></dd>
              </dl>
           </address>
		 </div>
      </div>
</div>      
{% include "shop/components/footer.html" %}
{% endblock %}

loban_loft/shop/templates/shop/index.html
{% extends "shop/base.html" %}

{% block title %}
SHOP
{% endblock %}

{% block content %}

	{% include "shop/components/header.html" %}
	{% include "shop/components/banner.html" %}
	{% include "shop/components/content.html" %}
	{% include "shop/components/blog.html" %}
	{% include "shop/components/footer.html" %}

{% endblock %}

loban_loft/shop/templates/shop/men.html
{% extends "shop/base.html" %}

{% block title %}
GANGA_GANGA | Каталог
{% endblock %}

{% block content %}

{% include "shop/components/header.html" %}
<div class="container">
<div class="women_main">
	<div class="col-md-9 w_content">

		{% include "shop/components/sort.html" %}

	{% for product in product_list %}
		{% include "shop/components/box.html" %}
	{% endfor %}

	</div>

	<!-- start sidebar -->
	<div class="col-md-3">
	  <div class="w_sidebar">


		{% include "shop/components/filter.html" %}

	  </div>
   </div>
	<div class="row mt-5">
  <div class="col-md-12 text-center">
    <div class="site-block-27">
      <ul>
          {% if page_obj.has_previous %}
              <li><a href="?page=1">&laquo;  </a></li>
              <li><a href="?page={{ page_obj.previous_page_number }}">&lt  </a></li>
          {% endif %}

        <a class="active" href="#">{{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</a>

        {% if page_obj.has_next %}
              <li><a href="?page={{ page_obj.next_page_number }}">&gt</a></li>
              <li><a href="?page={{ page_obj.paginator.num_pages }}"> &raquo;</a></li>
          {% endif %}

      </ul>
    </div>
  </div>
</div>
	<!-- start content -->
   <div class="clearfix"></div>
   <!-- end content -->
 </div>
</div>
{% include "shop/components/footer.html" %}
{% endblock %}

loban_loft/shop/templates/shop/single.html
{% load static %}



<!DOCTYPE HTML>
<html>
<head>
<title>GANGA_GANGA | О товаре</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Buy_shop Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href="{% static 'css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<!-- Custom Theme files -->
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' />
<script src="{% static 'js/simpleCart.min.js' %}"> </script>
<!-- Custom Theme files -->
<!--webfont-->
<link href='http://fonts.googleapis.com/css?family=Lato:100,200,300,400,500,600,700,800,900' rel='stylesheet' type='text/css'>
<script type="text/javascript" src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
<!-- start menu -->
<script src="{% static 'js/jquery.easydropdown.js' %}"></script>
<link href="{% static 'css/megamenu.css' %}" rel="stylesheet" type="text/css" media="all" />
<script type="text/javascript" src="{% static 'js/megamenu.js' %}"></script>
<script>$(document).ready(function(){$(".megamenu").megamenu();});</script>
<link rel="stylesheet" href="{% static 'css/etalage.css' %}">
<script src="{% static 'js/jquery.etalage.min.js' %}"></script>
<script>
			jQuery(document).ready(function($){

				$('#etalage').etalage({
					thumb_image_width: 300,
					thumb_image_height: 400,
					source_image_width: 900,
					source_image_height: 1200,
					show_hint: true,
					click_callback: function(image_anchor, instance_id){
						alert('Callback example:\nYou clicked on an image with the anchor: "'+image_anchor+'"\n(in Etalage instance: "'+instance_id+'")');
					}
				});

			});
		</script>
<!--initiate accordion-->
<script type="text/javascript">
	$(function() {

	    var menu_ul = $('.menu_drop > li > ul'),
	           menu_a  = $('.menu_drop > li > a');

	    menu_ul.hide();

	    menu_a.click(function(e) {
	        e.preventDefault();
	        if(!$(this).hasClass('active')) {
	            menu_a.removeClass('active');
	            menu_ul.filter(':visible').slideUp('normal');
	            $(this).addClass('active').next().stop(true,true).slideDown('normal');
	        } else {
	            $(this).removeClass('active');
	            $(this).next().stop(true,true).slideUp('normal');
	        }
	    });

	});
</script>
</head>
<body>


{% include "shop/components/header.html" %}
<div class="single_top">
	 <div class="container"> 
	      <div class="single_grid">
				<div class="grid images_3_of_2">
						<ul id="etalage">
							<li>
								<a href="optionallink.html">
									<img class="etalage_thumb_image" src="{{ product.image.url }}" class="img-responsive" />
									<img class="etalage_source_image" src="{{ product.image.url }}" class="img-responsive" title="" />
								</a>
							</li>
							{% for images in product.productimage_set.all %}

							<li>
								<img class="etalage_thumb_image" src="{{ images.images.url }}" class="img-responsive" />
								<img class="etalage_source_image" src="{{ images.images.url }}" class="img-responsive" title="" />
							</li>
							{% endfor %}

						</ul>
						 <div class="clearfix"></div>
				  </div>
				  <div class="desc1 span_3_of_2">

					<h1>{{ product.title }}</h1>
					<p>{{ product.description }}</p>

			         <div class="simpleCart_shelfItem">
			         	<div class="price_single">
						  <div class="head"><h2><span class="amount item_price">{{ product.price }}</span></h2></div>

					       <div class="clearfix"></div>
					     </div>
			               <!--<div class="single_but"><a href="" class="item_add btn_3" value=""></a></div>-->
			              <div class="size_2-right"><a href="#" class="item_add item_add1 btn_5" value="" /> Добавить в корзину </a></div>
			          
			         </div>
				</div>
          	    <div class="clearfix"></div>
          	   </div>

			 <ul class="menu_drop">

				<li class="item1"><a href="#"><img src="{% static 'images/product_arrow.png' %}">Дополнительная информация</a>
					<ul>
					    <li class="subitem2"><a href="#"> {{ product.descr }}</a></li>

					</ul>
				</li>

				<li class="item2"><a href="#"><img src="{% static 'images/product_arrow.png' %}">Отзывы ({{ product.reviews_set.count }})</a>
					<ul>
						{% for review in product.reviews_set.all %}
						<li class="subitem1"><a href="#"> <span class="amount item_price">{{ review.name }}:</span>{{ review.text }} </a></li>
						{% endfor %}

					</ul>
				</li>

	 		</ul>
		 {% if user.is_authenticated %}
		 <div class="contact-single">
                    <h3 class="editContent" style="outline: none; cursor: inherit;">
                                    <span class="sub-tittle editContent"
                                          style="outline: none; cursor: inherit;"></span>Оставить
                        отзыв</h3>
                    <form action="{% url 'add_review' product.id %}" method="post" class="mt-4">
                        {% csrf_token %}
                        <div class="form-group editContent">
                            <label for="contactcomment" class="editContent">
                                Ваш комментарий *
                            </label>
                            <textarea class="form-control border" rows="5" name="text"
                                      id="contactcomment" required=""></textarea>
                        </div>
                        <div class="d-sm-flex">
                            <div class="col-sm-6 form-group p-0 editContent">
                                <label for="contactusername" class="editContent">
                                    Имя *
                                </label>
                                <input type="text" class="form-control border" name="name"
                                       id="contactusername" required="">
                            </div>
<!--                            <div class="col-sm-6 form-group ml-sm-3 editContent">-->
<!--                                <label for="contactemail" class="editContent">-->
<!--                                    Email *-->
<!--                                </label>-->
<!--                                <input type="email" class="form-control border" name="email"-->
<!--                                       id="contactemail" required="">-->
<!--                            </div>-->
                        </div>
                        <button type="submit"
                                class="mt-3 btn btn-success btn-block py-3">
                            Отправить
                        </button>
                    </form>
                </div>
		 {% endif %}
   </div>

{% include "shop/components/footer.html" %}
</body>
</html>